server:
  port: 8080
  error:
    whitelabel:
      enabled: false  # false : 기본 error 페이지 비활성화 

spring: 
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/humble_project?serverTimezone=UTC&characterEncoding=UTF-8
    username: root  
    password: jt67f7!@
  jpa:
    properties:
      hibernate:                                
        dialect : org.hibernate.dialect.MariaDBDialect
      show_sql : true                           #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
      formate_sql : true                        #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
      use_sql_comments : true                   #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
    
mybatis:
  config-location: classpath:sqlmap/sqlmap-config.xml
  mapper-locations: classpath*:sqlmap/mappers/**/*.xml
  type-aliases-package: com.ipbyhj.dev
  
